parameters:

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Vdm\Bundle\LibraryFlysystemTransportBundle\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,vendor,Kernel.php}'

    Vdm\Bundle\LibraryFlysystemTransportBundle\Transport\FlysystemTransportFactory:
        arguments:
            $flysystemFactory: '@flysystem.adapter.lazy.factory'